spring.datasource.url=jdbc:mysql://localhost:3306/batch_demo2
spring.datasource.username=root
spring.datasource.password=21311a1988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
#spring.batch.job.names=recordProcessingJob,fileChunkingJob

logging.level.org.springframework.batch=INFO
logging.level.com.example.batchdemo=INFO

# AWS Region

aws.region=us-east-1
aws.s3.bucket-name=s3-demo-csv-learning
aws.s3.input-key=csv/sample.csv

# Local folder for Tasklet-based file chunking
file.chunk.output-dir=C:/Users/2472814/batch-file-chunks-stepfun
aws.kinesis.stream-name=batch-demo-stream
aws.s3.chunk-output-prefix=chunks/output