
spring.datasource.url=jdbc:mysql://localhost:3306/batchdemo
spring.datasource.username=root
spring.datasource.password=21311a1988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
spring.batch.job.names=recordProcessingJob

logging.level.org.springframework.batch=INFO
logging.level.com.example.batchdemo=INFO
